backend:
  name: github
  repo: Exxa1/astro-decap-template #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "http://astro-template-with-cms-test.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: datetime }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }
  - name: testblogs
    label: Blogs
    folder: src/content/blogs
    create: true
    format: frontmatter
    preview_path: blogs/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: datetime, time_format: false }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }
      

# source for optimizing images in sveltia cms: https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#optimizing-images-for-upload
media_libraries:
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
          width: 2048 # default: original size
          height: 2048 # default: original size
        svg:
          optimize: true